### ISSUE TITLE
Error reading file $FILENAME: Success

### ISSUE THREAD

**Issue by tidux** [flathub/io.github.cmus.cmus#6]
I am getting this error message attempting to play a musepack file in flatpak cmus.  I know it's not a permissions issue because my whole library is owned me:me and all the directories/folders between my homedir and the file are 755/644 respectively.  Other parts of my library play back correctly.  I'm reporting this as a Flatpak app bug because it seems relevant to the sandboxing of the application - unconfined and even other Flatpaks (the mpv flatpak from Flathub) can play these files back just fine so I know they're not corrupted.

```
$ cmus --plugins 
Input Plugins: /app/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /app/lib/cmus/op
  pulse
  alsa
```

**Comment by tidux** [comment]
After installing cmus through my system's package manager and performing no further changes to the music files, I was able to play them back through that version of cmus.  This is confirmed as a packaging error in the Flatpak version.

**Comment by X-m7** [comment]
Confirmed, the issue is that the musepack library was compiled incorrectly. I created a PR that fixes the issue for me, it would be great if you could try the test build linked there and confirm it works for you as well.

**Comment by tidux** [comment]
Thanks for the quick fix!  Works great.  Feel free to close this issue once the PR is merged and the resulting build is on Flathub.

**Comment by X-m7** [comment]
So I don't really have a way to know when exactly the update will be on Flathub, however according to [this](https://github.com/flathub/flathub/wiki/App-Maintenance#automatic-publishing-delay) it should be up in about 3 hours after the PR is merged. Simplest solution is probably to check tomorrow.

Anyway, thanks for reporting the issue and testing the fix!
